Marketplace
protokol/collectibles-mobile pull request #76
Opened 2021-05-11 09:21 UTC by cmayorga

## Summary

### What changes are being made?

Fixed PR#71 reviews
Changed Market home slider to button based menu
Added logic and UI to start an auction and to see open auctions
Several cosmetics and bugs fixed

### Why are these changes necessary?
To add the auctions feature

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [X] Ready to be merged

2021-06-07 15:05 UTC, amacar requested changes
Please make cleanup of the whole project (remove console logs, non-relevant code comments...) then it is ready to merge :)

2021-06-07 15:46 UTC, cmayorga commented on src/components/HomeMarket.tsx
> +    {submenu==="mybids" && (
I think this is not definitive, is part of the navigation issues i am working on.

2021-06-07 15:56 UTC, amacar commented on src/components/HomeMarket.tsx
> +    {submenu==="mybids" && (
Noted

2021-06-07 17:30 UTC, cmayorga commented on package.json
> +    "@opencensus/core": "0.0.22",
@protokol/nameservice-crypto is used at src/store/services/crypto.ts

2021-06-07 17:46 UTC, cmayorga commented on src/components/HomeMarket.tsx
> +    {submenu==="mybids" && (
I finally did the change to Enum

2021-06-07 18:02 UTC, cmayorga commented on package.json
> +    "perf_hooks": "^0.0.1",
"node-sass": "^5.0.0", is required to allow scss files

2021-06-08 07:34 UTC, amacar approved these changes

2021-06-08 07:35 UTC, merged